linter:
  rules:
    - always_declare_return_types: true
    - prefer_single_quotes: true
    - unnecessary_new: true
    - prefer_const_constructors: true
    - avoid_print: true
    - lines_longer_than_80_chars: true
    - public_member_api_docs: false
    - type_annotate_public_apis: true
    - prefer_final_fields: true
    - avoid_types_on_closure_parameters: true
    - unnecessary_this: true
    - prefer_is_empty: true
    - avoid_annotating_with_dynamic: true
    - prefer_const_literals_to_create_immutables: true
    - prefer_trailing_comma: true
    - sort_pub_dependencies: true
    - prefer_adjacent_string_concatenation: true
    - avoid_redundant_argument_values: true
    - prefer_mixin: true
    - use_key_in_widget_constructors: true

analyzer:
  errors:
    unused_import: warning
    dead_code: warning
    missing_return: error
    invalid_annotation_target: error
    unnecessary_getters_setters: warning
    unnecessary_lambdas: warning
    prefer_final_locals: warning
    prefer_const_constructors_in_immutables: warning
    prefer_const_declarations: warning
    prefer_final_fields: warning
    prefer_single_quotes: warning
    unnecessary_this: warning
    unnecessary_new: warning
    prefer_is_empty: warning
    avoid_print: warning
    avoid_types_on_closure_parameters: warning
    prefer_const_literals_to_create_immutables: warning
    prefer_trailing_comma: warning
    sort_pub_dependencies: warning
    prefer_adjacent_string_concatenation: warning
    avoid_redundant_argument_values: warning
    prefer_mixin: warning
    use_key_in_widget_constructors: warning